### ISSUE TITLE
Minor error in "Shader Texture LOD" section

### ISSUE THREAD

**Issue by selfshadow** [shrekshao/MoveWebGL1EngineToWebGL2#3]
In the texture LOD section, you're comparing texture2DLodEXT(..., lod) with texture(..., lodBias), but these are not equivalent: the former takes a direct LOD parameter, whereas the latter takes an LOD offset (bias). The new textureLod function in WebGL 2.0 / GLSL ES 3.0 is the one you should be referring to instead.

Other than that, nice article!

**Comment by shrekshao** [comment]
Thanks for pointing this out @selfshadow . I made a fix at https://github.com/shrekshao/MoveWebGL1EngineToWebGL2/commit/bbe869a1748ffdae0249ab8bf45e270e7756f6ad . I think that would be correct for now?

**Comment by selfshadow** [comment]
Yes, that looks good. Thanks!
